config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # event routes
  get "/events", to: "events#index", as: "events"   # this page shows all the events
  get "/events/new", to:"events#new", as: "new_event" # this page renders the form for a new event
  post "/events", to:"events#create"                  # this route creates the post request to create a new event
  get "/events/:id/edit", to: "events#edit", as: "edit_event" # this route renders the form to edit an event
  patch "/events/:id", to: "events#update", as: "update_event"
  get "/events/:id/tickets", to: "tickets#index", as: "event_tickets"   # when you click on an event you go to this page which shows all tickets for sale for an event
  get "events/:id/tickets/new", to: "tickets#new", as: "new_ticket"  # there is a button on the event_tickets page that takes you to a form to make a new ticket
  get "events/:id/tickets/bulk_new", to: "tickets#bulk_new", as: "bulk_tickets"
  post "/events/:id/tickets_bulk", to: "tickets#bulk_create", as: "bulk_create"
  post "/events/:id/tickets", to: "tickets#create"    # this creates a new ticket when you hit submit
  
  # ticket routes
  patch "/tickets/:id/pending", to: "tickets#mark_as_pending", as: "pending_ticket"  # on the individual event page each ticket for sale has a button when you click that button it changes the status to pending and adds your user id to the buyer_id
  get "/tickets/cart", to: "tickets#cart", as: "cart"   # in the navbar there is a shopping cart button that when clicked shows me all the tickets where buyer_id = my user_id and status = pending
  patch "/tickets/:id/cancel", to: "tickets#cancel", as: "cancel"  # in the cart you can cancel individual tickets to remove them from the cart
  patch "/tickets/", to: "tickets#mark_as_sold", as: "sold"          # on the shopping cart page there is a purchased button that when clicked changes the ticket status to sold, changes the buyer_id to nil, and changes the user_id to the current user
  # in the navbar there is a avatar icon that when clicked on takes me to my profile page
  get "tickets/my_listings", to: "tickets#my_listings", as: "my_listings" # on my profile page there is a link to this page that shows all the tickets that have my user_id and the for_sale or pending status
  get "/tickets/:id/edit", to: "tickets#edit", as: "edit_ticket"  # on my listings page you can click a button on any of the tickets to edit its price this button takes you to an edit page
  patch "/tickets/:id", to: "tickets#update", as: "update_ticket" # when you hit submit on the edit page it updates the tickets price and redirects to my listings
  patch "/tickets/:id/stop", to: "tickets#stop", as: "stop"   # I don't think you want to delete tickets.. just stop selling them...
  # delete "/tickets/:id", to: "tickets#destroy", as: "delete_ticket"   # on the my_listings page each ticket has a button to delete it
  get "tickets/my_tickets", to: "tickets#my_tickets", as: "my_tickets"    # on the profile page there is a link to a page that shows all of the tickets on my page that shows all the tickets with the current user_id and are sold
  patch "/tickets/:id/sell", to: "tickets#mark_as_for_sale", as: "sell_ticket"   # on the my tickets page each ticket has a button that changes the tickt status to for_sale
  get "tickets/:id/", to: "tickets#show", as: "show"   # on the tickets page each ticket has a button that takes you to the ticket view page
end

app/views/shared/_events.html.erb
<div class="container mt-2 mb-3 p-3 w-100 border shadow rounded">
<%= link_to event_tickets_path(event), class: "text-decoration-none text-body" do %>
    <div class="d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
            <%= image_tag "rock-concert-vibes-stockcake.png", size: "100x100" %>
            <div class="ms-3">
                <h5 class="mb-0"> <strong> <%= event.name %> </strong></h5>
                <p class="small"> <em><%= event.date.strftime("%e %B %Y") %>
                    @ <%= event.location %></em></p>
                <h5 class="my-0">
                <% if event.tickets.where(status: "for_sale").any? %>
                    <p class="small">Current average price:
                    <% avg_tickets = [] %>
                    <% event.tickets.where(status: "for_sale").each do |ticket| %>
                        <% avg_tickets << ticket.price %>
                    <% end %>
                        $ <%= avg_tickets.sum.fdiv(event.tickets.where(status: "for_sale").count).round(0) %>
                <% end %>
                </p>
                </h5> 
                <strong><%= event.tickets.where(status: "for_sale").count %> <em></em></strong>
                <% if event.tickets.where(status: "for_sale").count == 1 %>
                     ticket available
                <% else %>
                    tickets available
                <% end %>
            </div>
        </div>
        <div>
        </div>
    </div>
<% end %>
</div>

app/views/shared/_events_search_bar.html.erb
<div data-controller="search">
    <%= form_with url: events_path, method: :get, class: "d-flex my-3 border-radius", html: { data: { search_target: "form" } } do %>
      <%= text_field_tag  :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Search for events by name or location",
                          data: { search_target: "input" } %>
      <%= submit_tag "Search", name: "", class: "btn btn-success" %>
    <% end %>
    <div class="d-flex justify-content-end">
      <a href="" data-action="click->search#clear" class="text-decoration-none small">Clear search</a>
    </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show small" role="alert">
    <%= notice %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="ps-3 fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show small" role="alert">
    <%= alert %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="ps-3 fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<%= link_to root_path do %>
    <%= image_tag "gogogo_logo.png", size: "200x59", class: "d-block mx-auto" %>
<% end %>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel"><strong>Are you sure?</strong></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="d-flex align-items-center">
                <%# change img to cloudinary!! %>
                <img src="https://ichef.bbci.co.uk/images/ic/256xn/p01btpwf.jpg" style="width: 100px;" alt="">
                <p class="ps-3"><%= message %></p>
            </div>
            <div class="ms-2">
                <hr>
                <p class="small"><strong>Date:</strong> <%= ticket.event.date.strftime("%e %B %Y") %></p>
                <p class="small"><strong>Location:</strong> <%= ticket.event.location %></p>
                <p class="small"><strong>Price:</strong> $ <%= ticket.price.round(0) %></p>
            </div>
        </div>
        <p class="small ms-3"><em><%= footer %></em></p>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to "Confirm", path, method: :patch, class: "btn btn-primary" %>
        </div>
    </div>
    </div>
</div>