config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # event routes
  get "/events", to: "events#index", as: "events"   # this page shows all the events
  get "/events/new", to:"events#new", as: "new_event" # this page renders the form for a new event
  post "/events", to:"events#create"                  # this route creates the post request to create a new event
  get "/events/:id/edit", to: "events#edit", as: "edit_event" # this route renders the form to edit an event
  patch "/events/:id", to: "events#update", as: "update_event"
  get "/events/:id/tickets", to: "tickets#index", as: "event_tickets"   # when you click on an event you go to this page which shows all tickets for sale for an event
  get "events/:id/tickets/new", to: "tickets#new", as: "new_ticket"  # there is a button on the event_tickets page that takes you to a form to make a new ticket
  get "events/:id/tickets/bulk_new", to: "tickets#bulk_new", as: "bulk_tickets"
  post "/events/:id/tickets_bulk", to: "tickets#bulk_create", as: "bulk_create"
  post "/events/:id/tickets", to: "tickets#create"    # this creates a new ticket when you hit submit
  
  # ticket routes
  patch "/tickets/:id/pending", to: "tickets#mark_as_pending", as: "pending_ticket"  # on the individual event page each ticket for sale has a button when you click that button it changes the status to pending and adds your user id to the buyer_id
  get "/tickets/cart", to: "tickets#cart", as: "cart"   # in the navbar there is a shopping cart button that when clicked shows me all the tickets where buyer_id = my user_id and status = pending
  patch "/tickets/:id/cancel", to: "tickets#cancel", as: "cancel"  # in the cart you can cancel individual tickets to remove them from the cart
  patch "/tickets/", to: "tickets#mark_as_sold", as: "sold"          # on the shopping cart page there is a purchased button that when clicked changes the ticket status to sold, changes the buyer_id to nil, and changes the user_id to the current user
  # in the navbar there is a avatar icon that when clicked on takes me to my profile page
  get "tickets/my_listings", to: "tickets#my_listings", as: "my_listings" # on my profile page there is a link to this page that shows all the tickets that have my user_id and the for_sale or pending status
  get "/tickets/:id/edit", to: "tickets#edit", as: "edit_ticket"  # on my listings page you can click a button on any of the tickets to edit its price this button takes you to an edit page
  patch "/tickets/:id", to: "tickets#update", as: "update_ticket" # when you hit submit on the edit page it updates the tickets price and redirects to my listings
  patch "/tickets/:id/stop", to: "tickets#stop", as: "stop"   # I don't think you want to delete tickets.. just stop selling them...
  # delete "/tickets/:id", to: "tickets#destroy", as: "delete_ticket"   # on the my_listings page each ticket has a button to delete it
  get "tickets/my_tickets", to: "tickets#my_tickets", as: "my_tickets"    # on the profile page there is a link to a page that shows all of the tickets on my page that shows all the tickets with the current user_id and are sold
  patch "/tickets/:id/sell", to: "tickets#mark_as_for_sale", as: "sell_ticket"   # on the my tickets page each ticket has a button that changes the tickt status to for_sale
  get "tickets/:id/", to: "tickets#show", as: "show"   # on the tickets page each ticket has a button that takes you to the ticket view page
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user

  enum ticket_category: { vip: 0, general_admission: 1, balcony: 2, early_bird: 3 }
  enum status: { for_sale: 0, pending: 1, sold: 2 }

  validates :ticket_category, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :status, presence: true
  validates :ticket_number, uniqueness: true, presence: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[mark_as_pending mark_as_for_sale destroy stop cancel edit update show]
  skip_before_action :authenticate_user!, only: :index

  # GET /events/:id/tickets
  def index
    @event = Event.find(params[:id])
    @tickets = policy_scope(@event.tickets).where(status: "for_sale")
    @markers = [{ lat: @event.latitude, lng: @event.longitude }]
  end

  # GET /events/:id/tickets/new
  def new
    @event = Event.find(params[:event_id])
    @ticket = Ticket.new
    authorize @ticket
  end

  # GET /events/:id/tickets/bulk_new
  def bulk_new
    @event = Event.find(params[:event_id])
    @ticket = Ticket.new
    authorize @ticket
  end

  # POST /events/:id/tickets
  def create
    @event = Event.find(params[:id])
    updated_params = ticket_params
    updated_params[:status] = ticket_params[:status].to_i
    @ticket = @event.tickets.build(updated_params)
    authorize @ticket
    # @ticket.user = current_user # Assign the ticket to the logged-in user

    if @ticket.save
      redirect_to event_tickets_path(@event), notice: "Ticket created successfully!"
    else
      redirect_to event_tickets_path(@event), alert: @ticket.errors.full_messages.to_sentence
    end
  end

  # POST /events/:id/tickets
  def bulk_create
    @event = Event.find(params[:id])
    quantity = params[:quantity].to_i
    errors = []

    quantity.times do
      updated_params = ticket_params
      updated_params[:status] = ticket_params[:status].to_i
      updated_params[:ticket_number] = SecureRandom.hex(6).upcase
      @ticket = @event.tickets.build(updated_params)
      authorize @ticket
      # @ticket.user = current_user # Assign the ticket to the logged-in user

      errors << ticket.errors.full_messages.to_sentence unless @ticket.save
    end

    if errors.empty?
      redirect_to event_tickets_path(@event), notice: "#{quantity} tickets created successfully!"
    else
      redirect_to event_tickets_path(@event), alert: "Some tickets failed to create: #{errors.uniq.join(', ')}"
    end
  end

  # PATCH /tickets/:id/pending
  def mark_as_pending
    authorize @ticket
    if @ticket.update(status: "pending", buyer_id: current_user.id)
      redirect_to event_tickets_path(@ticket.event), notice: "Ticket marked as pending!"
    else
      redirect_to event_tickets_path(@ticket.event), alert: "Unable to update ticket."
    end
  end

  # PATCH /tickets/:id/sell
  def mark_as_for_sale
    authorize @ticket
    if @ticket.update(status: :for_sale)
      redirect_to my_tickets_path, notice: "Ticket is now for sale!"
    else
      redirect_to my_tickets_path, alert: "Unable to update ticket."
    end
  end

  # GET /tickets/cart
  def cart
    @tickets = Ticket.where(buyer_id: current_user.id, status: :pending)
    authorize @tickets
  end

  def cancel
    authorize @ticket
    if @ticket.update(status: :for_sale, buyer_id: nil)
      redirect_to cart_path, notice: "Sale canceled. Ticket is now available for sale."
    else
      redirect_to cart_path, alert: "Unable to cancel the sale of this ticket."
    end
  end

  # PATCH /tickets
  def mark_as_sold
    tickets = Ticket.where(buyer_id: current_user.id, status: :pending)
    authorize tickets
    if tickets.update_all(status: "sold", buyer_id: nil, user_id: current_user.id)
      redirect_to my_tickets_path, notice: "Tickets purchased successfully!"
    else
      redirect_to cart_path, alert: "Unable to complete the purchase."
    end
  end

  # GET /tickets/my_listings
  def my_listings
    @tickets = Ticket.where(user_id: current_user.id).where(status: %i[for_sale pending])
    authorize @tickets
  end

  # Not in use
  # DELETE /tickets/:id
  def destroy
    @ticket.destroy
    redirect_to my_listings_path, notice: "Ticket deleted successfully!"
  end

  # PATCH "/tickets/:id/stop"
  def stop
    authorize @ticket
    if @ticket.update(status: :sold)
      redirect_to my_listings_path, notice: "Ticket removed from sale. You can access it in the 'My Tickets' section."
    else
      redirect_to my_listings_path, alert: "Unable to stop the sale of this ticket."
    end
  end

  def edit
    # @ticket set before
    authorize @ticket
  end

  def update
    authorize @ticket
    if @ticket.update(price: params[:ticket][:price], status: :for_sale)
      redirect_to my_listings_path, notice: "Ticket price updated successfully!"
    else
      Rails.logger.debug "Validation Errors: #{@ticket.errors.full_messages}"
      render :edit, status: :unprocessable_entity
    end
  end

  # GET /tickets/my_tickets
  def my_tickets
    @tickets = Ticket.where(user_id: current_user.id, status: "sold")
    authorize @tickets
  end

  def show
    # @ticket provided by set ticket
    authorize @ticket
  end

  private

  # Strong parameters for ticket creation
  def ticket_params
    params.require(:ticket).permit(:ticket_number, :price, :ticket_category, :qr_code, :status, :user_id)
  end

  # Set a ticket for actions requiring a ticket ID
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/views/tickets/bulk_new.html.erb
<div class="container mt-4">
  <h1>Create New Ticket for <%= @event.name %></h1>
  
  <%= simple_form_for @ticket, url: bulk_create_path, method: :post do |f| %>
    
    <!-- Ticket Quantity -->
    <div class="mb-3">
      <%= f.label :price, "Quantity" %>
      <%= number_field_tag :quantity, step: 1, class: "form-control", placeholder: "Enter ticket quntity" %>
    </div>

    <!-- Price -->
    <div class="mb-3">
      <%= f.label :price, "Price" %>
      <%= f.number_field :price, step: 1, class: "form-control", placeholder: "Enter ticket price" %>
    </div>

    <!-- Ticket Category -->
    <div class="mb-3">
      <%= f.label :ticket_category, "Category" %>
      <%= f.select :ticket_category, Ticket.ticket_categories.keys.map { |key| [key.titleize, key] }, {}, class: "form-select" %>
    </div>

    <!-- Status (Hidden) -->
    <%= f.hidden_field :status, value: Ticket.statuses[:for_sale] %>

    <!-- Event ID (Hidden) -->
    <%# <%= f.hidden_field :event_id, value: @event.id %>

    <!-- User ID (Hidden) -->
    <%= f.hidden_field :user_id, value: current_user.id %>

    <!-- Submit Button -->
    <div class="mt-3">
      <%= f.submit "Create Ticket", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/tickets/cart.html.erb
<div class="container mt-4 border shadow p-3">
  <h1>Shopping Cart</h1>

  <hr>
<% if @tickets.any? %>
  <table class="table" data-controller="modal">
    <thead>
      <tr>
        <th>Ticket Number</th>
        <th>Category</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.ticket_number %></td>
          <td><%= ticket.ticket_category.titleize %></td>
          <td>$<%= ticket.price %></td>
          <td>
            <button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-action="click->modal#show"> Remove item </button>
            <%= render "shared/modal", ticket: ticket,
                                                path: cancel_path(ticket),
                                                message: "Remove your #{ticket.ticket_category.titleize} ticket for #{ticket.event.name}",
                                                footer: "(Remember that you can add it to your cart again from the Event.)"%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= button_to "Purchase All", sold_path, method: :patch, class: "btn btn-success" %>
<% else %>
  <p>Your shopping cart is empty.
    <%= link_to "Explore events to purchase the best ticket for you!", events_path, class: "text-decoration-none" %> </p>
<% end %>
</div>

app/views/tickets/edit.html.erb
<div class="container mt-4 border shadow p-3">
  <h1>Modify your ticket's price</h1>
  <hr>
  <p><strong>Event:</strong> <%= @ticket.event.name %></p>
  <p><strong>Date:</strong> <%= @ticket.event.date.strftime("%d %B %Y") %></p>
  <p><strong>Category:</strong> <%= @ticket.ticket_category.titleize %></p>
  <p><strong>Tickets still for sale:</strong> <%= @ticket.event.tickets.where(status: "for_sale").count %></p>
  <p><strong>Current average price:</strong>
                <% avg_tickets = [] %>
                <% @ticket.event.tickets.where(status: "for_sale").each do |ticket| %>
                    <% avg_tickets << ticket.price %>
                <% end %>
                <% if @ticket.event.tickets.where(status: "for_sale").any? %>
                    $ <%= avg_tickets.sum.fdiv(@ticket.event.tickets.where(status: "for_sale").count).round(0) %>
                <%end%>
                </p>
  <hr>
  <strong>
  <%= simple_form_for @ticket, url: update_ticket_path(@ticket), method: :patch do |f| %>
    
    <div class="mb-3">
      <%= f.label :price, "Your current price", class: "mb-3" %>
      <%= f.number_field :price, step: 1, class: "form-control", placeholder: "Enter new price" %>
    </div>
    </strong>
    <div class="mt-3">
      <%= f.submit "Update Price", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tickets/index.html.erb
<div class="d-flex mt-5 justify-content-center align-items-center" style="width: 100%; height: 200px;">
  <div class="d-flex justify-content-center align-items-center gap-5 w-75">

    <div class="d-flex flex-column justify-content-center text-start" style="width: 50%;">
      <h5>Tickets for <%= @event.name %></h5>
      <p>Date: <%= @event.date.strftime("%B %d, %Y") %></p>
      <p>Location: <%= @event.location %></p>
      <p>Capacity: <%= @event.capacity %></p>
    </div>

    <div class="d-flex justify-content-center align-items-center" style="width: 50%;">
      <%= cl_image_tag @event.photo.key, class: "img-fluid rounded-4", alt: "Responsive image", style: "width: 80%; height: auto; object-fit: cover;"%>
    </div>
  </div>
</div>


<div class="container mt-4">


  <%= link_to "Create New Ticket", new_ticket_path(event_id: @event.id), class: "btn btn-success my-3" %>
  <% if policy(@tickets).bulk_create? %>
    <%= link_to bulk_tickets_path(event_id: @event.id), class: "btn btn-primary my-3" do %>
      <i class="fa-solid fa-ticket"></i> Create tickets in bulk
      <% end %>
  <% end %>
  <% if policy(@event).update? %>
  <%= link_to edit_event_path, { class: "btn btn-success" } do %>
    <i class="fa-solid fa-user"></i> Edit event details
  <% end %>
  <% end %>
  <hr>

  <h2>Available Tickets</h2>
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-6">
        <% if @tickets.any? %>
          <table class="table table-striped">
            <thead>
              <tr style="margin-bottom:15px">
                <th>Ticket Number</th>
                <th>Category</th>
                <th>Price</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @tickets.each do |ticket| %>
                <tr>
                  <td><%= ticket.ticket_number %></td>
                  <td><%= ticket.ticket_category.titleize %></td>
                  <td>$<%= ticket.price %></td>
                  <td>
                    <%= button_to "Add to cart", pending_ticket_path(ticket), method: :patch, class: "btn btn-primary rounded-3" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No tickets available for this event.</p>
        <% end %>
      </div>


      <div class="col-6">
        <div class="ml-5 " style="width: 100%; height: 400px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tickets/my_listings.html.erb
<div class="container mt-4 border shadow p-3">
  <h1>My Listings</h1>
  <hr>
  <% if @tickets.any? %>
    <table class="table table-striped" data-controller="modal">
      <thead>
        <tr>
          <th></th>
          <th>Event Name</th>
          <th>Date</th>
          <th>Category</th>
          <th>Price</th>
          <th>Ticket Number</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tickets.each do |ticket| %>
          <tr>
            <td>
                <%= button_to show_path(ticket), method: :get, class: "btn btn-outline btn-sm" do %>
                  <i class="fa-solid fa-qrcode"></i>
                <% end %>
            </td>
            <td><%= ticket.event.name %></td>
            <td><%= ticket.event.date.strftime("%e %B %Y") %></td>
            <td><%= ticket.ticket_category.titleize %></td>
            <td>$<%= ticket.price.round(0) %></td>
            <td><%= ticket.ticket_number %></td>
            <td class="d-flex">
              <button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-action="click->modal#show"> Stop sale </button>
              <%= render "shared/modal", ticket: ticket,
                                                path: stop_path(ticket),
                                                message: "You are about to stop the sale of your #{ticket.ticket_category.titleize} ticket for #{ticket.event.name}",
                                                footer: "(Remember that you can resell this ticket from My tickets.)" %>
              <%# <%= button_to "Stop Sale", stop_path(ticket), method: :patch, data: { turbo_confirm: "Are you sure you want to stop the sale of this ticket?" }, class: "btn btn-warning btn-sm" %>
              <%= link_to "Edit", edit_ticket_path(ticket), class: "btn btn-success btn-sm ms-3" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>You currently have no tickets listed for sale or pending. <%= link_to "Explore events to purchase the best ticket for you!", events_path, class: "text-decoration-none" %></p>
  <% end %>
</div>

app/views/tickets/my_tickets.html.erb
<div class="container mt-4 border shadow p-3">
  <h1>My Tickets</h1>
  <hr>
  <% if @tickets.any? %>
    <table class="table table-striped" data-controller="modal">
      <thead>
        <tr>
          <th></th>
          <th>Event Name</th>
          <th>Date</th>
          <th>Category</th>
          <th>Price</th>
          <th>Ticket Number</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tickets.each do |ticket| %>
          <tr>
            <td>
              <%= button_to show_path(ticket), method: :get, class: "btn btn-outline btn-sm" do %>
                <i class="fa-solid fa-qrcode"></i>
                <% end %>
            </td>
            <td><%= ticket.event.name %></td>
            <td><%= ticket.event.date.strftime("%d %B %Y") %></td>
            <td><%= ticket.ticket_category.titleize %></td>
            <td>$ <%= ticket.price.round(0) %></td>
            <td><%= ticket.ticket_number %></td>
            <td>
              <button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-action="click->modal#show"> Resell </button>
              <%= render "shared/modal", ticket: ticket,
                                                path: sell_ticket_path(ticket),
                                                message: "You are about to resell your #{ticket.ticket_category.titleize} ticket for #{ticket.event.name}",
                                                footer: "(Remember that you can modify the selling price in My listings.)"%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>You have no tickets purchased. <%= link_to "Explore events to purchase the best ticket for you!", events_path, class: "text-decoration-none" %></p>
  <% end %>
</div>

app/views/tickets/new.html.erb
<div class="container mt-4">
  <h1>Create New Ticket for <%= @event.name %></h1>
  
  <%= simple_form_for @ticket, url: event_tickets_path, method: :post do |f| %>
    <!-- Ticket Number -->
    <div class="mb-3">
      <%= f.label :ticket_number, "Ticket Number" %>
      <%= f.text_field :ticket_number, class: "form-control", placeholder: "Enter ticket number" %>
    </div>

    <!-- Price -->
    <div class="mb-3">
      <%= f.label :price, "Price" %>
      <%= f.number_field :price, step: 0.01, class: "form-control", placeholder: "Enter ticket price" %>
    </div>

    <!-- Ticket Category -->
    <div class="mb-3">
      <%= f.label :ticket_category, "Category" %>
      <%= f.select :ticket_category, Ticket.ticket_categories.keys.map { |key| [key.titleize, key] }, {}, class: "form-select" %>
    </div>

    <!-- Status (Hidden) -->
    <%= f.hidden_field :status, value: Ticket.statuses[:for_sale] %>

    <!-- Event ID (Hidden) -->
    <%# <%= f.hidden_field :event_id, value: @event.id %>

    <!-- User ID (Hidden) -->
    <%= f.hidden_field :user_id, value: current_user.id %>

    <!-- Submit Button -->
    <div class="mt-3">
      <%= f.submit "Create Ticket", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/tickets/show.html.erb
<!-- Banner -->
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://wallpaperaccess.com/full/2489692.jpg)">

</div>

<!-- Category Header -->
<div class="mt-5 border-bottom text-center">
	<h2>Your Ticket</h2>
  <p class="small"> Print this page or download it to be scanned at the event</p>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-4 text-center border rounded p-3 m-5 shadow">
    <h3 class="mt-3 mb-3"><%= @ticket.event.name %></h3>
    <p class="mb-3"><%= @ticket.event.date.strftime("%d %B %Y") %></p>
    <p class="mb-3"><%= @ticket.event.location %></p>
    <p class="mb-3">Category: <%= @ticket.ticket_category.titleize %></p>
    <p class="mb-3">Price: $<%= @ticket.price %></p>
    <div class="mt-5 mb-5">
      <%= RQRCode::QRCode.new(@ticket.ticket_number).as_svg(
                                                              offset: 0,
                                                              color: '000',
                                                              shape_rendering: 'crispEdges',
                                                              standalone: true,
                                                              module_size: 7
                                                              ).html_safe %>
    </div>
  </div>
</div>